import {
  User,
  Course,
  Topic,
  StudentTopicView,
  LearningCapsule,
  QuizDelivery,
  QuizAttemptResult,
  Recommendation,
  LearningPath,
  StudentPerformance,
  StudentDashboardData,
  TrainerDashboardData,
  CourseAnalyticsData,
  AdminDashboardData,
} from '../types';

export const mockUsers: Record<string, User> = {
  admin: {
    id: 'usr-admin-01',
    email: 'admin@learnflow.edu',
    full_name: 'Dr. Eleanor Vance (Admin)',
    role: 'ADMIN',
    is_active: true,
  },
  trainer: {
    id: 'usr-trainer-01',
    email: 'trainer@learnflow.edu',
    full_name: 'Prof. Alan Turing',
    role: 'TRAINER',
    is_active: true,
    employee_code: 'TRN-ENG-042',
    department: 'Computer Science & Artificial Intelligence',
  },
  student1: {
    id: 'usr-student-01',
    email: 'student1@learnflow.edu',
    full_name: 'Alex Chen',
    role: 'STUDENT',
    is_active: true,
    student_code: 'STU-2026-001',
    institution_name: 'National Institute of Technology',
    current_level: 'Senior Undergraduate',
  },
  student2: {
    id: 'usr-student-02',
    email: 'student2@learnflow.edu',
    full_name: 'Sophia Martinez',
    role: 'STUDENT',
    is_active: true,
    student_code: 'STU-2026-002',
    institution_name: 'National Institute of Technology',
    current_level: 'First-Year Undergraduate',
  },
};

export const mockCourse: Course = {
  id: 'crs-ml-101',
  trainer_id: 'usr-trainer-01',
  title: 'Introduction to Machine Learning & Neural Networks',
  description: 'Master end-to-end predictive modeling, loss optimization, and deep neural network architectures.',
  thumbnail_url: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=800&auto=format&fit=crop&q=60',
  status: 'PUBLISHED',
  published_at: '2026-08-20T00:00:00Z',
  created_at: '2026-08-15T00:00:00Z',
  updated_at: '2026-08-20T00:00:00Z',
  topic_count: 4,
  enrolled_count: 24,
};

export const mockTopics: Topic[] = [
  {
    id: 'top-1',
    course_id: 'crs-ml-101',
    title: '1. Mathematical Foundations for Machine Learning',
    description: 'Linear algebra essentials, vector spaces, dot products, and multivariate gradients.',
    sequence_no: 1,
    estimated_minutes: 15,
    status: 'PUBLISHED',
    created_at: '2026-08-16T00:00:00Z',
    prerequisite_ids: [],
    capsule_id: 'cap-1',
    quiz_id: 'quiz-1',
  },
  {
    id: 'top-2',
    course_id: 'crs-ml-101',
    title: '2. Linear & Logistic Regression',
    description: 'Formulating cost functions, mean squared error, cross-entropy, and gradient descent optimization.',
    sequence_no: 2,
    estimated_minutes: 20,
    status: 'PUBLISHED',
    created_at: '2026-08-17T00:00:00Z',
    prerequisite_ids: ['top-1'],
    capsule_id: 'cap-2',
    quiz_id: 'quiz-2',
  },
  {
    id: 'top-3',
    course_id: 'crs-ml-101',
    title: '3. Neural Network Architecture & Backpropagation',
    description: 'Multilayer perceptrons, activation functions (ReLU, Sigmoid), and reverse-mode automatic differentiation.',
    sequence_no: 3,
    estimated_minutes: 25,
    status: 'PUBLISHED',
    created_at: '2026-08-18T00:00:00Z',
    prerequisite_ids: ['top-2'],
    capsule_id: 'cap-3',
    quiz_id: 'quiz-3',
  },
  {
    id: 'top-4',
    course_id: 'crs-ml-101',
    title: '4. Deep Learning Optimization & Regularization',
    description: 'Adam and RMSProp optimizers, dropout, batch normalization, and mitigating overfitting.',
    sequence_no: 4,
    estimated_minutes: 25,
    status: 'PUBLISHED',
    created_at: '2026-08-19T00:00:00Z',
    prerequisite_ids: ['top-3'],
    capsule_id: 'cap-4',
    quiz_id: 'quiz-4',
  },
];

export const mockStudentTopicsView: StudentTopicView[] = [
  {
    id: 'top-1',
    course_id: 'crs-ml-101',
    title: '1. Mathematical Foundations for Machine Learning',
    description: 'Linear algebra essentials, vector spaces, dot products, and multivariate gradients.',
    sequence_no: 1,
    estimated_minutes: 15,
    is_locked: false,
    mastery_score: 92.5,
    strength_status: 'STRONG',
    has_completed_capsule: true,
    has_completed_quiz: true,
    capsule_id: 'cap-1',
    quiz_id: 'quiz-1',
    prerequisite_ids: [],
  },
  {
    id: 'top-2',
    course_id: 'crs-ml-101',
    title: '2. Linear & Logistic Regression',
    description: 'Formulating cost functions, mean squared error, cross-entropy, and gradient descent optimization.',
    sequence_no: 2,
    estimated_minutes: 20,
    is_locked: false,
    mastery_score: 89.0,
    strength_status: 'STRONG',
    has_completed_capsule: true,
    has_completed_quiz: true,
    capsule_id: 'cap-2',
    quiz_id: 'quiz-2',
    prerequisite_ids: ['top-1'],
  },
  {
    id: 'top-3',
    course_id: 'crs-ml-101',
    title: '3. Neural Network Architecture & Backpropagation',
    description: 'Multilayer perceptrons, activation functions (ReLU, Sigmoid), and reverse-mode automatic differentiation.',
    sequence_no: 3,
    estimated_minutes: 25,
    is_locked: false,
    mastery_score: 0.0,
    strength_status: 'UNCERTAIN',
    has_completed_capsule: false,
    has_completed_quiz: false,
    capsule_id: 'cap-3',
    quiz_id: 'quiz-3',
    prerequisite_ids: ['top-2'],
  },
  {
    id: 'top-4',
    course_id: 'crs-ml-101',
    title: '4. Deep Learning Optimization & Regularization',
    description: 'Adam and RMSProp optimizers, dropout, batch normalization, and mitigating overfitting.',
    sequence_no: 4,
    estimated_minutes: 25,
    is_locked: true,
    lock_reason: "Requires >= 65% mastery in '3. Neural Network Architecture & Backpropagation'",
    mastery_score: 0.0,
    strength_status: 'UNCERTAIN',
    has_completed_capsule: false,
    has_completed_quiz: false,
    capsule_id: 'cap-4',
    quiz_id: 'quiz-4',
    prerequisite_ids: ['top-3'],
  },
];

export const mockCapsule: LearningCapsule = {
  id: 'cap-1',
  topic_id: 'top-1',
  version: 1,
  level: 'STANDARD',
  title: 'Foundations: Vectors, Matrices & Loss',
  status: 'PUBLISHED',
  estimated_minutes: 5,
  created_by: 'usr-trainer-01',
  published_at: '2026-08-20T00:00:00Z',
  created_at: '2026-08-20T00:00:00Z',
  sections: [
    {
      id: 'sec-1',
      capsule_id: 'cap-1',
      section_type: 'SUMMARY',
      sequence_no: 1,
      content_json: {
        explanation:
          'Linear algebra and multivariate calculus form the core computational framework of artificial intelligence. High-dimensional vector spaces represent features, and transformation matrices map input inputs into hidden states.\n\nOptimization requires multivariate gradients: partial derivatives indicate the direction of greatest increase. Gradient descent subtracts this vector to iteratively converge upon minimal error.',
      },
    },
    {
      id: 'sec-2',
      capsule_id: 'cap-1',
      section_type: 'KEY_POINTS',
      sequence_no: 2,
      content_json: {
        points: [
          'A vector represents N-dimensional coordinates or token embeddings.',
          'The dot product quantifies directional cosine similarity.',
          'The gradient contains all first-order partial derivatives of the cost function.',
          'Parameter update rule: W = W - alpha * dW.',
        ],
        objectives: [
          'Understand vector geometric properties.',
          'Formulate the steepest descent equation.',
        ],
      },
    },
    {
      id: 'sec-3',
      capsule_id: 'cap-1',
      section_type: 'SIMPLE_EXPLANATION',
      sequence_no: 3,
      content_json: {
        simple_explanation:
          'Think of gradient descent like being lost on a foggy mountain at night. You cannot see the entire landscape, but you can feel the slope directly under your boots. Taking small steps in the steepest downward direction guarantees you will reach the valley floor.',
      },
    },
    {
      id: 'sec-4',
      capsule_id: 'cap-1',
      section_type: 'EXAMPLE',
      sequence_no: 4,
      content_json: {
        example:
          'In semantic search and vector databases, query sentences and documents are embedded as 768-dimensional vectors. Dot product calculations allow nearest-neighbor lookups in sub-10ms across millions of documents.',
      },
    },
    {
      id: 'sec-5',
      capsule_id: 'cap-1',
      section_type: 'RECAP',
      sequence_no: 5,
      content_json: {
        recap_question:
          'Why does choosing an excessively large learning rate (alpha) cause gradient descent to oscillate or diverge?',
      },
    },
  ],
  video: {
    id: 'vid-1',
    capsule_id: 'cap-1',
    script: 'Welcome to this 90-second micro-lesson on Mathematical Foundations...',
    duration_seconds: 90,
    status: 'READY',
    video_url: 'videos/sample_micro_lesson.mp4',
  },
};

export const mockQuizDelivery: QuizDelivery = {
  id: 'quiz-1',
  topic_id: 'top-1',
  type: 'QUICK',
  title: 'Math Foundations Knowledge Check',
  pass_score: 70.0,
  status: 'PUBLISHED',
  questions: [
    {
      id: 'q-1',
      question_text: 'What does a gradient vector represent in multivariate calculus?',
      question_type: 'MCQ',
      difficulty: 'EASY',
      sequence_no: 1,
      marks: 1.0,
      options: [
        { id: 'opt-1', option_text: 'Direction of steepest ascent of the cost function', sequence_no: 1 },
        { id: 'opt-2', option_text: 'The global minimum scalar value', sequence_no: 2 },
        { id: 'opt-3', option_text: 'The determinant of the input matrix', sequence_no: 3 },
        { id: 'opt-4', option_text: 'The total count of training samples', sequence_no: 4 },
      ],
    },
    {
      id: 'q-2',
      question_text: 'Why do we subtract the gradient during parameter updates in gradient descent?',
      question_type: 'MCQ',
      difficulty: 'MEDIUM',
      sequence_no: 2,
      marks: 1.0,
      options: [
        { id: 'opt-5', option_text: 'To step in the direction of steepest descent (minimizing error)', sequence_no: 1 },
        { id: 'opt-6', option_text: 'To increase model parameters exponentially', sequence_no: 2 },
        { id: 'opt-7', option_text: 'To invert the Hessian matrix directly', sequence_no: 3 },
        { id: 'opt-8', option_text: 'To remove negative numbers from the dataset', sequence_no: 4 },
      ],
    },
  ],
};

export const mockStudentDashboard: StudentDashboardData = {
  student_name: 'Alex Chen',
  current_level: 'Senior Undergraduate',
  overall_progress: 72.5,
  streak_days: 4,
  total_quizzes_taken: 8,
  average_score: 91.2,
  enrolled_courses_count: 1,
  active_recommendation: {
    id: 'rec-1',
    student_id: 'usr-student-01',
    course_id: 'crs-ml-101',
    topic_id: 'top-3',
    topic_title: '3. Neural Network Architecture & Backpropagation',
    course_title: 'Introduction to Machine Learning & Neural Networks',
    recommendation_type: 'NEXT_TOPIC',
    priority: 95.0,
    reason_code: 'MASTERY_EXCEEDED_PROGRESS',
    explanation:
      "Outstanding! You demonstrated 89% mastery on 'Linear & Logistic Regression'. You are ready to unlock Topic 3: 'Neural Network Architecture & Backpropagation'.",
    generated_by: 'RULE_ENGINE_V1',
    status: 'ACTIVE',
    created_at: '2026-09-07T12:00:00Z',
  },
  recent_recommendations: [
    {
      id: 'rec-1',
      student_id: 'usr-student-01',
      course_id: 'crs-ml-101',
      topic_id: 'top-3',
      topic_title: '3. Neural Network Architecture & Backpropagation',
      course_title: 'Introduction to Machine Learning & Neural Networks',
      recommendation_type: 'NEXT_TOPIC',
      priority: 95.0,
      reason_code: 'MASTERY_EXCEEDED_PROGRESS',
      explanation: 'Unlock Next Module: Neural Networks',
      generated_by: 'RULE_ENGINE_V1',
      status: 'ACTIVE',
      created_at: '2026-09-07T12:00:00Z',
    },
    {
      id: 'rec-0',
      student_id: 'usr-student-01',
      course_id: 'crs-ml-101',
      topic_id: 'top-2',
      topic_title: '2. Linear & Logistic Regression',
      course_title: 'Introduction to Machine Learning & Neural Networks',
      recommendation_type: 'TARGETED_PRACTICE',
      priority: 88.0,
      reason_code: 'TARGETED_REINFORCEMENT',
      explanation: 'Reinforce Cost Function Derivation',
      generated_by: 'RULE_ENGINE_V1',
      status: 'COMPLETED',
      created_at: '2026-09-05T10:00:00Z',
    },
  ],
  weak_topics: [],
  strong_topics: [
    {
      student_id: 'usr-student-01',
      topic_id: 'top-1',
      topic_title: '1. Mathematical Foundations for Machine Learning',
      course_id: 'crs-ml-101',
      course_title: 'Introduction to Machine Learning & Neural Networks',
      mastery_score: 92.5,
      confidence_score: 85.0,
      strength_status: 'STRONG',
      attempt_count: 2,
      recent_accuracy: 100.0,
      completion_quality: 100.0,
      last_assessed_at: '2026-09-05T14:30:00Z',
    },
    {
      student_id: 'usr-student-01',
      topic_id: 'top-2',
      topic_title: '2. Linear & Logistic Regression',
      course_id: 'crs-ml-101',
      course_title: 'Introduction to Machine Learning & Neural Networks',
      mastery_score: 89.0,
      confidence_score: 85.0,
      strength_status: 'STRONG',
      attempt_count: 2,
      recent_accuracy: 100.0,
      completion_quality: 100.0,
      last_assessed_at: '2026-09-07T11:45:00Z',
    },
  ],
  recent_quiz_attempts: [
    { id: 'att-1', quiz_title: 'Linear & Logistic Regression Checkpoint', score: 2.0, percentage: 100.0, submitted_at: '2026-09-07T11:45:00Z', passed: true },
    { id: 'att-2', quiz_title: 'Math Foundations Knowledge Check', score: 2.0, percentage: 100.0, submitted_at: '2026-09-05T14:30:00Z', passed: true },
  ],
};

export const mockTrainerDashboard: TrainerDashboardData = {
  total_courses: 1,
  total_students: 24,
  active_capsules_count: 4,
  pending_drafts_count: 1,
  average_quiz_score: 78.4,
  difficult_topics: [
    {
      topic_id: 'top-2',
      topic_title: '2. Linear & Logistic Regression',
      course_title: 'Introduction to Machine Learning & Neural Networks',
      struggling_percent: 32.0,
      average_mastery: 58.2,
      total_students: 24,
    },
  ],
  recent_student_activity: [
    { student_name: 'Alex Chen', quiz_title: 'Linear Regression Checkpoint', score: 100.0, date: 'Sep 07, 11:45' },
    { student_name: 'Sophia Martinez', quiz_title: 'Linear Regression Checkpoint', score: 40.0, date: 'Sep 06, 16:10' },
    { student_name: 'David Kim', quiz_title: 'Math Foundations Check', score: 85.0, date: 'Sep 06, 09:20' },
  ],
};

export const mockAdminDashboard: AdminDashboardData = {
  total_users: 28,
  total_students: 24,
  total_trainers: 3,
  total_admins: 1,
  total_courses: 2,
  total_capsules: 8,
  total_quizzes_taken: 64,
  total_materials_processed: 12,
  recent_audit_logs: [
    { id: 'log-1', action: 'USER_REGISTERED', entity_type: 'USER', entity_id: 'usr-student-24', timestamp: '2026-09-08T08:15:00Z' },
    { id: 'log-2', action: 'CAPSULE_PUBLISHED', entity_type: 'CAPSULE', entity_id: 'cap-4', timestamp: '2026-09-07T18:00:00Z' },
    { id: 'log-3', action: 'COURSE_CREATED', entity_type: 'COURSE', entity_id: 'crs-ml-101', timestamp: '2026-09-05T10:00:00Z' },
  ],
  system_health: {
    database: 'HEALTHY (PostgreSQL 16)',
    redis: 'OPERATIONAL (Cache & Queues)',
    ai_gateway: 'ONLINE (Structured Outputs Validated)',
  },
};

export const mockTrainerQuizzes: import('../types').QuizTrainer[] = [
  {
    id: 'quiz-1',
    topic_id: 'top-1',
    topic_title: '1. Mathematical Foundations',
    course_title: 'Introduction to Machine Learning & Neural Networks',
    type: 'QUICK',
    title: 'Math Foundations Knowledge Check',
    pass_score: 70.0,
    status: 'PUBLISHED',
    version: 1,
    created_at: '2026-09-01T10:00:00Z',
    questions: [
      {
        id: 'q-1',
        question_text: 'What does a gradient vector represent in multivariate calculus?',
        question_type: 'MCQ',
        difficulty: 'EASY',
        explanation: 'The gradient vector points in the direction of greatest rate of increase of the scalar field.',
        sequence_no: 1,
        marks: 1.0,
        options: [
          { id: 'opt-1', option_text: 'Direction of steepest ascent of the cost function', is_correct: true, sequence_no: 1 },
          { id: 'opt-2', option_text: 'The global minimum scalar value', is_correct: false, sequence_no: 2 },
          { id: 'opt-3', option_text: 'The determinant of the input matrix', is_correct: false, sequence_no: 3 },
          { id: 'opt-4', option_text: 'The total count of training samples', is_correct: false, sequence_no: 4 },
        ],
      },
      {
        id: 'q-2',
        question_text: 'Why do we subtract the gradient during parameter updates in gradient descent?',
        question_type: 'MCQ',
        difficulty: 'MEDIUM',
        explanation: 'Subtracting moves parameters opposite to ascent, steering towards error minimization.',
        sequence_no: 2,
        marks: 1.0,
        options: [
          { id: 'opt-5', option_text: 'To step in the direction of steepest descent (minimizing error)', is_correct: true, sequence_no: 1 },
          { id: 'opt-6', option_text: 'To increase model parameters exponentially', is_correct: false, sequence_no: 2 },
          { id: 'opt-7', option_text: 'To invert the Hessian matrix directly', is_correct: false, sequence_no: 3 },
          { id: 'opt-8', option_text: 'To remove negative numbers from the dataset', is_correct: false, sequence_no: 4 },
        ],
      },
    ],
  },
  {
    id: 'quiz-2',
    topic_id: 'top-2',
    topic_title: '2. Linear & Logistic Regression',
    course_title: 'Introduction to Machine Learning & Neural Networks',
    type: 'QUICK',
    title: 'Linear & Logistic Regression Checkpoint',
    pass_score: 70.0,
    status: 'PUBLISHED',
    version: 1,
    created_at: '2026-09-03T11:30:00Z',
    questions: [
      {
        id: 'q-3',
        question_text: 'Which activation function maps real numbers to probabilities in standard logistic regression?',
        question_type: 'MCQ',
        difficulty: 'EASY',
        explanation: 'Sigmoid / Logistic function outputs values bounded in (0, 1).',
        sequence_no: 1,
        marks: 1.0,
        options: [
          { id: 'opt-9', option_text: 'Sigmoid / Logistic function: 1 / (1 + e^-z)', is_correct: true, sequence_no: 1 },
          { id: 'opt-10', option_text: 'ReLU activation function', is_correct: false, sequence_no: 2 },
          { id: 'opt-11', option_text: 'Identity function f(x) = x', is_correct: false, sequence_no: 3 },
          { id: 'opt-12', option_text: 'Hyperbolic Secant', is_correct: false, sequence_no: 4 },
        ],
      },
      {
        id: 'q-4',
        question_text: 'What loss function is primarily used for binary classification in logistic regression?',
        question_type: 'MCQ',
        difficulty: 'MEDIUM',
        explanation: 'Binary Cross-Entropy (Log Loss) measures likelihood under predicted probabilities.',
        sequence_no: 2,
        marks: 1.0,
        options: [
          { id: 'opt-13', option_text: 'Binary Cross-Entropy (Log Loss)', is_correct: true, sequence_no: 1 },
          { id: 'opt-14', option_text: 'Mean Squared Error (MSE)', is_correct: false, sequence_no: 2 },
          { id: 'opt-15', option_text: 'Huber Loss with delta=1', is_correct: false, sequence_no: 3 },
          { id: 'opt-16', option_text: 'Hinge Loss for max margin', is_correct: false, sequence_no: 4 },
        ],
      },
    ],
  },
  {
    id: 'quiz-3',
    topic_id: 'top-3',
    topic_title: '3. Neural Network Architecture & Backpropagation',
    course_title: 'Introduction to Machine Learning & Neural Networks',
    type: 'PRACTICE',
    title: 'Neural Networks & Backprop Quiz',
    pass_score: 70.0,
    status: 'PUBLISHED',
    version: 1,
    created_at: '2026-09-05T14:00:00Z',
    questions: [
      {
        id: 'q-5',
        question_text: 'What mathematical rule is the backbone of the backpropagation algorithm?',
        question_type: 'MCQ',
        difficulty: 'EASY',
        explanation: 'The calculus chain rule allows computing derivatives of composite functions.',
        sequence_no: 1,
        marks: 1.0,
        options: [
          { id: 'opt-17', option_text: 'The Chain Rule of Calculus', is_correct: true, sequence_no: 1 },
          { id: 'opt-18', option_text: "L'Hopital's Rule", is_correct: false, sequence_no: 2 },
          { id: 'opt-19', option_text: "Bayes' Theorem", is_correct: false, sequence_no: 3 },
          { id: 'opt-20', option_text: 'Taylor Series Expansion', is_correct: false, sequence_no: 4 },
        ],
      },
      {
        id: 'q-6',
        question_text: 'Why is ReLU often preferred over Sigmoid in deep hidden layers?',
        question_type: 'MCQ',
        difficulty: 'MEDIUM',
        explanation: 'ReLU avoids vanishing gradient for positive activations and is computationally efficient.',
        sequence_no: 2,
        marks: 1.0,
        options: [
          { id: 'opt-21', option_text: 'Mitigates the vanishing gradient problem for positive inputs', is_correct: true, sequence_no: 1 },
          { id: 'opt-22', option_text: 'Bounds outputs strictly between 0 and 1', is_correct: false, sequence_no: 2 },
          { id: 'opt-23', option_text: 'Guarantees convex global optimization', is_correct: false, sequence_no: 3 },
          { id: 'opt-24', option_text: 'Eliminates the need for bias terms', is_correct: false, sequence_no: 4 },
        ],
      },
      {
        id: 'q-7',
        question_text: 'What happens during the forward pass in neural networks?',
        question_type: 'MCQ',
        difficulty: 'MEDIUM',
        explanation: 'Inputs are multiplied by weights, biases are added, activations applied to produce output prediction.',
        sequence_no: 3,
        marks: 1.0,
        options: [
          { id: 'opt-25', option_text: 'Inputs propagate layer by layer to compute activations and the final loss', is_correct: true, sequence_no: 1 },
          { id: 'opt-26', option_text: 'Weights are updated with learning rate scaling', is_correct: false, sequence_no: 2 },
          { id: 'opt-27', option_text: 'Gradients flow backwards from output to inputs', is_correct: false, sequence_no: 3 },
          { id: 'opt-28', option_text: 'Weights are randomly reinitialized', is_correct: false, sequence_no: 4 },
        ],
      },
    ],
  },
  {
    id: 'quiz-4',
    topic_id: 'top-4',
    topic_title: '4. Optimization & Regularization',
    course_title: 'Introduction to Machine Learning & Neural Networks',
    type: 'QUICK',
    title: 'Optimization & Regularization Quiz',
    pass_score: 70.0,
    status: 'DRAFT',
    version: 1,
    created_at: '2026-09-08T09:00:00Z',
    questions: [
      {
        id: 'q-8',
        question_text: 'What is the primary effect of L1 regularization (Lasso) compared to L2 regularization (Ridge)?',
        question_type: 'MCQ',
        difficulty: 'MEDIUM',
        explanation: 'L1 penalty promotes exact sparsity by driving less important feature weights to zero.',
        sequence_no: 1,
        marks: 1.0,
        options: [
          { id: 'opt-29', option_text: 'Encourages sparse weights (drives coefficients to exactly zero)', is_correct: true, sequence_no: 1 },
          { id: 'opt-30', option_text: 'Shrinks weights evenly without setting them to zero', is_correct: false, sequence_no: 2 },
          { id: 'opt-31', option_text: 'Increases the learning rate dynamically', is_correct: false, sequence_no: 3 },
          { id: 'opt-32', option_text: 'Prevents underfitting by expanding model capacity', is_correct: false, sequence_no: 4 },
        ],
      },
      {
        id: 'q-9',
        question_text: 'How does Dropout regularize a deep neural network during training?',
        question_type: 'MCQ',
        difficulty: 'MEDIUM',
        explanation: 'By randomly dropping units during training, it prevents co-adaptation of features.',
        sequence_no: 2,
        marks: 1.0,
        options: [
          { id: 'opt-33', option_text: 'Randomly deactivates a fraction of neurons per mini-batch to prevent co-adaptation', is_correct: true, sequence_no: 1 },
          { id: 'opt-34', option_text: 'Deletes training rows from the dataset permanently', is_correct: false, sequence_no: 2 },
          { id: 'opt-35', option_text: 'Normalizes activations to zero mean and unit variance', is_correct: false, sequence_no: 3 },
          { id: 'opt-36', option_text: 'Forces weights to stay strictly non-negative', is_correct: false, sequence_no: 4 },
        ],
      },
    ],
  },
];
