from app.schemas.auth import (
    UserRegisterRequest,
    UserLoginRequest,
    RefreshTokenRequest,
    UserResponse,
    AuthResponse,
    TokenPayload,
    UserUpdateRequest,
)
from app.schemas.course import CourseCreate, CourseUpdate, CourseResponse, CourseEnrollmentResponse
from app.schemas.topic import TopicCreate, TopicUpdate, TopicResponse, StudentTopicView
from app.schemas.material import MaterialResponse, MaterialChunkResponse, JobStatusResponse
from app.schemas.capsule import (
    CapsuleSectionCreate,
    CapsuleSectionResponse,
    LearningCapsuleCreate,
    LearningCapsuleUpdate,
    LearningCapsuleResponse,
    CapsuleProgressUpdate,
    VideoResponse,
)
from app.schemas.quiz import (
    QuizOptionCreate,
    QuizOptionPublic,
    QuizOptionTrainer,
    QuizQuestionCreate,
    QuizQuestionPublic,
    QuizQuestionTrainer,
    QuizCreate,
    QuizUpdate,
    QuizDeliveryResponse,
    QuizTrainerResponse,
    QuizAttemptSubmit,
    QuizAttemptResultResponse,
)
from app.schemas.adaptive import (
    RecommendationResponse,
    LearningPathItemResponse,
    LearningPathResponse,
    StudentPerformanceResponse,
    StudentDashboardResponse,
)
from app.schemas.ai import (
    AIGenerationRequest,
    StructuredCapsuleOutput,
    StructuredQuizOutput,
    StructuredQuizQuestion,
    StructuredTopicExtractionOutput,
    StructuredVideoScript,
)
from app.schemas.analytics import (
    TrainerDashboardResponse,
    CourseAnalyticsResponse,
    AdminDashboardResponse,
)

__all__ = [
    "UserRegisterRequest",
    "UserLoginRequest",
    "RefreshTokenRequest",
    "UserResponse",
    "AuthResponse",
    "TokenPayload",
    "UserUpdateRequest",
    "CourseCreate",
    "CourseUpdate",
    "CourseResponse",
    "CourseEnrollmentResponse",
    "TopicCreate",
    "TopicUpdate",
    "TopicResponse",
    "StudentTopicView",
    "MaterialResponse",
    "MaterialChunkResponse",
    "JobStatusResponse",
    "CapsuleSectionCreate",
    "CapsuleSectionResponse",
    "LearningCapsuleCreate",
    "LearningCapsuleUpdate",
    "LearningCapsuleResponse",
    "CapsuleProgressUpdate",
    "VideoResponse",
    "QuizOptionCreate",
    "QuizOptionPublic",
    "QuizOptionTrainer",
    "QuizQuestionCreate",
    "QuizQuestionPublic",
    "QuizQuestionTrainer",
    "QuizCreate",
    "QuizUpdate",
    "QuizDeliveryResponse",
    "QuizTrainerResponse",
    "QuizAttemptSubmit",
    "QuizAttemptResultResponse",
    "RecommendationResponse",
    "LearningPathItemResponse",
    "LearningPathResponse",
    "StudentPerformanceResponse",
    "StudentDashboardResponse",
    "AIGenerationRequest",
    "StructuredCapsuleOutput",
    "StructuredQuizOutput",
    "StructuredQuizQuestion",
    "StructuredTopicExtractionOutput",
    "StructuredVideoScript",
    "TrainerDashboardResponse",
    "CourseAnalyticsResponse",
    "AdminDashboardResponse",
]
